### ISSUE TITLE
E220-400T22S Having Error on Serial1

### ISSUE THREAD

**Issue by krishank652** [nihinihikun/E220-900T22S-JP_Arduino#4]
Hi Dear,

I used this library for working on module Ebyte E220-40022S. I am getting compilation error.

![image](https://github.com/nihinihikun/E220-900T22S-JP_Arduino/assets/157563241/83685e07-387a-450d-945f-8881632ca2ff)

```
Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "Arduino Uno"
C:\Users\Krishan Kumar\Documents\Arduino\libraries\E220_900T22S_JP-1.0.0\example\test1\test1.ino: In function 'void setup()':
test1:14:5: error: 'Serial1' was not declared in this scope
     Serial1.begin(9600);
     ^~~~~~~
C:\Users\Krishan Kumar\Documents\Arduino\libraries\E220_900T22S_JP-1.0.0\example\test1\test1.ino:14:5: note: suggested alternative: 'Serial'
     Serial1.begin(9600);
     ^~~~~~~
     Serial
exit status 1
'Serial1' was not declared in this scope
This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

Please help me to solve the issue. Thanks

**Comment by nihinihikun** [comment]
Hi,krishank652,

Thank you for using this library. You use arduino UNO R3 , right? Arduino UNO, atmega328 has only one UART, that is talking with  USB-devices. Then "Serial1" is not avairable. It is good to use software serial. 


- See below if you know about serial.

https://www.arduino.cc/reference/en/language/functions/communication/serial/ 

- See below if you know about software serial.

https://docs.arduino.cc/learn/built-in-libraries/software-serial/

**Comment by krishank652** [comment]
Dear @nihinihikun,

Thank you for your prompt response!

As a novice with Arduino UNO, could you kindly provide guidance on how to implement the code? Specifically, could you direct me on where to make necessary updates in both the code and library files? Your assistance is greatly appreciated.

Thank you once again.

**Comment by krishank652** [comment]
Dear @nihinihikun ,

Please help me How can I implement software serial. Give me idea to implement it. I read supportive documents as your shared. But I don't know How can I do it.

Can you tell me please, In library where I need to update it.

Thanks

**Comment by nihinihikun** [comment]
Dear @krishank652 

Sorry for the late reply. The previous version of this library supported only Serial1. I've updated the library to support both SoftwareSerial and HardwareSerial. Please install version 2.0.0. You can now use the E220 with an Arduino UNO by following the example in softwareserialuse/softwareserialuse.ino.

Thanks

**Comment by nihinihikun** [comment]
Dear @krishank652

Sorry! I found bugs, I fixed them. Please use v2.0.1

**Comment by krishank652** [comment]
Thanks for the updation of library.

I tried it and updated pin no.: `SoftwareSerial mySerial(2, 3); // RX, TX` . Found some issue.

Error occur while compilation:

```
Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "Arduino Uno"
C:\Users\Krishan Kumar\Documents\Arduino\libraries\E220-900T22S-JP_Arduino-main\src\config_E220.cpp: In member function 'int config_E220::ReadResister(byte, byte, byte*)':
C:\Users\Krishan Kumar\Documents\Arduino\libraries\E220-900T22S-JP_Arduino-main\src\config_E220.cpp:29:13: error: 'Serial1' was not declared in this scope
     _length=Serial1.write(set_data, 3);
             ^~~~~~~
C:\Users\Krishan Kumar\Documents\Arduino\libraries\E220-900T22S-JP_Arduino-main\src\config_E220.cpp:29:13: note: suggested alternative: 'Serial'
     _length=Serial1.write(set_data, 3);
             ^~~~~~~
             Serial
C:\Users\Krishan Kumar\Documents\Arduino\libraries\E220-900T22S-JP_Arduino-main\src\config_E220.cpp: In member function 'int config_E220::WriteResister(byte, byte, byte*)':
C:\Users\Krishan Kumar\Documents\Arduino\libraries\E220-900T22S-JP_Arduino-main\src\config_E220.cpp:57:5: error: 'Serial1' was not declared in this scope
     Serial1.write(set_data, _length+3);
     ^~~~~~~
C:\Users\Krishan Kumar\Documents\Arduino\libraries\E220-900T22S-JP_Arduino-main\src\config_E220.cpp:57:5: note: suggested alternative: 'Serial'
     Serial1.write(set_data, _length+3);
     ^~~~~~~
     Serial
C:\Users\Krishan Kumar\Documents\Arduino\libraries\E220-900T22S-JP_Arduino-main\src\config_E220.cpp: In member function 'int config_E220::SetTemporaryResister(byte, byte, byte*)':
C:\Users\Krishan Kumar\Documents\Arduino\libraries\E220-900T22S-JP_Arduino-main\src\config_E220.cpp:83:5: error: 'Serial1' was not declared in this scope
     Serial1.write(set_data, _length+3);
     ^~~~~~~
C:\Users\Krishan Kumar\Documents\Arduino\libraries\E220-900T22S-JP_Arduino-main\src\config_E220.cpp:83:5: note: suggested alternative: 'Serial'
     Serial1.write(set_data, _length+3);
     ^~~~~~~
     Serial
C:\Users\Krishan Kumar\Documents\Arduino\libraries\E220-900T22S-JP_Arduino-main\src\config_E220.cpp: In member function 'void config_E220::SetDefault()':
C:\Users\Krishan Kumar\Documents\Arduino\libraries\E220-900T22S-JP_Arduino-main\src\config_E220.cpp:100:5: error: 'Serial1' was not declared in this scope
     Serial1.write(default_config_data, 11);
     ^~~~~~~
C:\Users\Krishan Kumar\Documents\Arduino\libraries\E220-900T22S-JP_Arduino-main\src\config_E220.cpp:100:5: note: suggested alternative: 'Serial'
     Serial1.write(default_config_data, 11);
     ^~~~~~~
     Serial
exit status 1
Error compiling for board Arduino Uno.


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

**Comment by nihinihikun** [comment]
Sorry, I overlooked the fact that the Arduino IDE compiles all library files regardless of their relation. I fixed config_E220.cpp. As a result, you should now be able to compile successfully with version 2.0.2."

**Comment by krishank652** [comment]
Thank you, I successfully compiled the SoftwareSerial example. Much appreciated.

My objective is to send data to a receiver device with a unique address, ensuring that only that specific device can receive the message. Could you please advise on how to implement addressing in the code for both the transmitter and receiver devices?

1. For a setup with two devices (1 transmitter and 1 receiver), should I assign the same address to both sides, or is it necessary to define different addresses for the transmitter and receiver?
2. In the scenario of having two or more devices, how can I address and establish communication among them? (e.g., 2 transmitters and 1 receiver)
3. Do I need to configure key parameters using the Ebyte software, as shown in the screenshot below?  I confused because I saw in the program there is a addressing.

Your assistance is greatly appreciated. Thank you.

![image](https://github.com/nihinihikun/E220-900T22S-JP_Arduino/assets/157563241/639c3950-07cd-43a0-816d-063a0a8a3c23)

**Comment by nihinihikun** [comment]
I don't know about E220-400T22S/D,but I think generally, radio module should have own id.  (Please see the datasheet)

**Comment by krishank652** [comment]
I believe you've created a dedicated library for the E220-900T22S module. Both my module and the library module are identical, except for the frequency difference. Each radio module has its own ID or key, which we can configure using the software screenshot I provided.

My only question is, how can I instruct the transmitter device to send data only to that specific device?
