### ISSUE TITLE
E220-400T22S Not receving data.

### ISSUE THREAD

**Issue by krishank652** [nihinihikun/E220-900T22S-JP_Arduino#6]
Hello,

I've been working with the `softwareserial` library and I've set up the wiring for my Arduino module accordingly, modifying the RX and TX pins as follows: `SoftwareSerial mySerial(2, 3); // RX, TX`.

However, despite my efforts, I'm encountering difficulties receiving messages from the transmitter device. Could you kindly share the code for both the transmitter and receiver with me?

Any assistance you can provide would be greatly appreciated. Thank you in advance for your help.

**Comment by krishank652** [comment]
Hello @nihinihikun,

I'm currently working on a collage project that involves the Ebyte Module, and I've encountered a need for specific coding to facilitate communication between a transmitter and receiver. Given your expertise, I'm reaching out to see if you would be interested in developing the necessary code for this project. 

_**I am willing to compensate you for your time and expertise. Could you kindly share your contact information so we can discuss this further?**_

Here are the requirements for the Transmitter and Receiver code:

**Transmitter Code Needs:**
1. Capability to send structured data wirelessly.
2. Enter sleep mode after data transmission.
3. Transmit data every minute.
4. Equipped with a unique address and must recognize the unique address of the target device (Receiver).

**Receiver Code Needs:**
1. Ability to receive structured data.
2. Must possess a unique address.

**Additionally, the system should be designed to accommodate:**
- One transmitter and one receiver.
- One transmitter and multiple receivers.
- Multiple transmitters and one receiver.

**Important Consideration:**
In an environment with multiple devices, it is crucial that there is no interference among them. Devices should only connect with their predefined transmitter(s) and receiver(s).

Your expertise would be invaluable in achieving a solution that meets these requirements. Please let me know if you're interested in collaborating on this project and how I can reach you to discuss the details further.

Thank you for considering this request.

Best regards,

**Comment by nihinihikun** [comment]
Hello krishank652,
Check about this.

- Is correct-connect between UNO and E220? (I often mistake to connect RX-TX)
- I recomend you to connect LED between 3.3V-AUXpin. This LED help you to know whether E220 send or receive messages . If E220 is able to get message or send it, LED blink.
- When you set configuration, was  M0,M1pin  LOW?
- When you want to use E220 as Transmitter/receiver,  is  M0,M1 pin LOW?

**Comment by nihinihikun** [comment]
Hello krishank652,
You can get Transmitter and Receiver code at Examples. SoftwareSerial.ino work  both Transmitter and Receiver.
